### ISSUE TITLE
Global Variables are Evil

### ISSUE THREAD

**Issue by see-coder** [see-coder/Dynamic-Programming#1]
9726ef7a5b0f9554c20fa19e1992b61b90f8231a

Here the previous function call is having an impact on the next function call. 
This function is assuming that memo is a global variable, but why so?
And what would be the best solution to this problem?

**Comment by hello-arun** [comment]
Problems which are critical need to be addressed more clearly. The line **Here the previous function call is having an impact on the next function call.** lacks clarity. 

Now we come to solution! Same problem has also been asked in the past in several posts such as 

* https://stackoverflow.com/questions/70302322/why-adding-memo-in-recursion-problem-gives-wrong-result-while-removing-memo-give
* https://stackoverflow.com/questions/65428535/why-does-this-solution-work-in-javascript-but-not-in-python-dynamic-programmin

But even after reading these posts you won's get any satisfactory insight, (Although some solutions are proposed but they will leave you in fear). The proper solution although is provided in these links

* https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/
* https://docs.python-guide.org/writing/gotchas/
* https://betterprogramming.pub/the-problem-with-mutable-types-as-default-values-in-functions-in-python-81ca88ff4d91

Definitely read it out, and in the future make it a habit to follow these guidelines.

**Comment by hello-arun** [comment]
Although it is not standard or the best practice but to be somewhat different from the internet trend I propose following

```python
# memoized solution
def can_sum(target_sum, numbers, memo=True):
    if memo == True:
        memo = {}
# No chagne in the rest
```

**Comment by see-coder** [comment]
Thank you @hello-arun for this wonderful and detailed solution!
